name: Update mirrors

on:
  schedule:
    # 7am UTC = 9am CET, 3am EDT, 0am PDT − should be light hours globally for WikiCFP.
    - cron: '0 7 * * *'
  workflow_dispatch:


jobs:
  update:
    name: Update mirrors
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python3 -m pip install breezy fastimport
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        path: libvterm
        ref: main
        fetch-depth: 0

    - name: Import upstream bazaar
      run: |
        while read remote branch; do
          echo Getting bazaar branch $remote to git branch $branch
          python3 -m breezy -Ossl.cert_reqs=none checkout https://bazaar.leonerd.org.uk/c/$remote bazaar-leonerd-$remote
          python3 -m breezy fast-export --plain -b $branch bazaar-leonerd-$remote | git -C libvterm fast-import --force

          # Git insert a newline after a message with e.g. git commit -m 'foo'. So does the neovim/libvterm repo
          # when importing bazaar commits. However fast-import doesn’t, so add them after the fact.
          git -C libvterm filter-branch -f --msg-filter 'cat ; echo' --tag-name-filter 'cat' $branch

          git -C libvterm merge-base --is-ancestor origin/$branch $branch
        done <<EOF
        libvterm bazaar
        libvterm.WIP-REFLOW bazaar-reflow
        EOF

    - name: Import nvim fork
      run: |
        git -C libvterm fetch https://github.com/neovim/libvterm master  2>&1 | cat
        git -C libvterm branch nvim FETCH_HEAD

        git -C libvterm merge-base --is-ancestor origin/nvim nvim

    - name: Import vim fork
      env:
        FILTER_BRANCH_SQUELCH_WARNING: 1
      run: |
        git -C libvterm fetch https://github.com/vim/vim master  2>&1 | cat

        # Split into a new “orphan” branch (--onto= with our previous branch does not work),
        # the prefix to exist even though we’re not on a relevant branch.
        mkdir -p libvterm/src/libvterm
        git -C libvterm subtree -q split FETCH_HEAD --prefix=src/libvterm --branch=vim

        # Get info of the first commits in the orphan branch and the target branch
        parent=`git -C libvterm merge-base origin/vim origin/bazaar`
        stub=`git -C libvterm log --format=%H origin/vim ^$parent | tail -n1`
        graft=`git -C libvterm log --format=%H vim | tail -n1`

        # Rebase and reset committer info
        git -C libvterm rebase -q --onto $stub $graft vim
        git -C libvterm filter-branch -f --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE" GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"' vim ^$parent

        git -C libvterm merge-base --is-ancestor origin/vim vim

    - name: Push mirrors to upstream branches
      run: |
        git -C libvterm push origin --tags bazaar nvim vim
