name: Update mirrors

on:
  schedule:
    # 7am UTC = 9am CET, 3am EDT, 0am PDT − should be light hours globally for WikiCFP.
    - cron: '0 7 * * *'
  workflow_dispatch:


jobs:
  update:
    name: Update mirrors
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo apt-get install python3-fastimport python3-breezy git-filter-repo

    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        path: libvterm
        ref: main
        fetch-depth: 0

    - name: Fetch upstream bazaar
      run: |
        git init bazaar-import
        while IFS=, read remote branch; do
          echo Getting bazaar branch $remote to git branch $branch
          python3 -m breezy -Ossl.cert_reqs=none checkout https://bazaar.leonerd.org.uk/c/$remote bazaar-leonerd-$remote
          python3 -m breezy fast-export --plain -b $branch bazaar-leonerd-$remote | git -C bazaar-import fast-import --force
        done < libvterm/bazaar-branches.csv

        # fast-import seems to remove quotes in names when compared to git pull bzr:: used by neovim (since their change in commits end of Oct. 2023)
        # so re-insert quotes with filter-repo
        git -C bazaar-import filter-repo --force --name-callback "return name.replace(b'Paul LeoNerd Evans', b'Paul \"LeoNerd\" Evans')"

    - name: Update bazaar refs in the repo
      run: |
        while IFS=, read remote branch; do
          git -C libvterm fetch ../bazaar-import/ $branch:refs/heads/$branch
          git -C libvterm merge-base --is-ancestor origin/$branch $branch
        done < libvterm/bazaar-branches.csv

        # Recreate the revision numbers
        mkdir -p libvterm/.git/refs/bazaar-revision
        start=`git -C libvterm rev-list --first-parent --count origin/bazaar | xargs echo 1 + | bc`
        git -C libvterm rev-list --first-parent bazaar ^origin/bazaar | tac | nl -v $start | while read n sha; do
          echo $sha > libvterm/.git/refs/bazaar-revision/$n
        done

    - name: Import nvim fork
      run: |
        git -C libvterm fetch https://github.com/neovim/libvterm mirror  2>&1 | cat
        git -C libvterm branch nvim FETCH_HEAD

        git -C libvterm merge-base --is-ancestor origin/nvim nvim

    - name: Import vim fork
      env:
        FILTER_BRANCH_SQUELCH_WARNING: 1
      run: |
        git -C libvterm fetch https://github.com/vim/vim master  2>&1 | cat

        # Split into a new “orphan” branch (--onto= with our previous branch does not work),
        # the prefix to exist even though we’re not on a relevant branch.
        mkdir -p libvterm/src/libvterm
        git -C libvterm subtree -q split FETCH_HEAD --prefix=src/libvterm --branch=vim

        # Get info of the first commits in the orphan branch and the target branch
        parent=`git -C libvterm merge-base origin/vim origin/bazaar`
        stub=`git -C libvterm rev-list --first-parent origin/vim ^$parent | tail -n1`
        graft=`git -C libvterm rev-list --first-parent vim | tail -n1`

        # Rebase and reset committer info
        git -C libvterm rebase -q --onto $stub $graft vim
        git -C libvterm filter-branch -f --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE" GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"' vim ^$parent

        git -C libvterm merge-base --is-ancestor origin/vim vim

    - name: Push mirrors to upstream branches
      run: |
        # nvim
        git -C libvterm push origin --tags bazaar vim refs/bazaar-revision/*:refs/bazaar-revision/*
